"""
Module: lambda_function.py

This module contains functions for handling date and time operations.
"""

import datetime  # pylint: disable=missing-module-docstring



def lambda_handler(event, context):
    """
    Lambda function handler for generating a unique training job name.

    Parameters:
        event (dict): The event data passed to the Lambda function.
            It should contain a key 'PrefixName' representing the prefix for the training job name.
        context (LambdaContext): The runtime information about the Lambda function invocation.

    Returns:
        str: A unique training job name generated by combining the provided prefix
             with the current timestamp in the format 'PrefixName-YYYYMMDDHHMMSS'.
    """
    prefix_name = event['PrefixName']
    training_job_name = str(prefix_name) + '-' + datetime.datetime.utcnow().strftime('%Y%m%d%H%M%S')
    return training_job_name
